# Generated by Django 6.0.3 on 2026-03-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_film_options_alter_rating_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='TMDB ID'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster_url',
            field=models.URLField(blank=True, null=True, verbose_name='Постер'),
        ),
    ]
